### ISSUE TITLE
Leaving an area in a certain direction does not properly register

### ISSUE THREAD

**Issue by dyzzy** [Relliktsohg/CuboidPlugin#1]
This relates to the position check in playerLeaves(), where the player's position is checked against the cuboid's coordinates. In the X direction, player.getX() can return the same value as coords[0] resulting in one cuboid boundary that does not respond to a player's departure with the farewell message, and does not remove the player from the list of occupants.

**Comment by dyzzy** [comment]
Isn't this position check kind of redundant, too? The player position is already checked to obtain the cuboid in the first place.

**Comment by dyzzy** [comment]
Didn't mean to close this, but it's a minor issue anyways.

**Comment by Relliktsohg** [comment]
You're right, I need to change the way this works.
The reason why I check the coordinates on leave is in case of nested cuboids : when the player appears to leave a cuboid to enter another.
I needed to only trigger the farewell message if the player actually left the boundaries.
